name: Build and Cache

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # exécuter le nettoyage tous les dimanches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: ''

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  cleanup-cache:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Clear old caches
        run: |
          # Cette section peut être automatisée pour supprimer manuellement des caches
          echo "Vérification des caches obsolètes et suppression si nécessaire."
